const data = {
    SaleToPOIRequest:{
        MessageHeader:{
            MessageClass:"Service",
            MessageCategory:"Print",
            MessageType:"Request",
            ServiceID:"{{$randomInt}}",
            SaleID:"TESTPOS",
            POIID: "V400cPlus-402023788",
            ProtocolVersion:"3.0"
        },
        PrintRequest:{
            PrintOutput:{
                OutputContent:{
                    OutputText:[
                        {
                            Color:"White",
                            CharacterWidth:"SingleWidth",
                            CharacterHeight:"SingleHeight",
                            CharacterStyle:"Bold",
                            Alignment:"Centred",
                            EndOfLineFlag:true,
                            Text:"Hi Luke"
                        },
                        {
                            Color:"White",
                            CharacterWidth:"SingleWidth",
                            CharacterHeight:"SingleHeight",
                            CharacterStyle:"Normal",
                            Alignment:"Left",
                            EndOfLineFlag:true,
                            Text:"Some explanation about the receipt (# %^& @/: $ £ Ä)"
                        },
                        {
                            Color:"White",
                            CharacterWidth:"SingleWidth",
                            CharacterHeight:"SingleHeight",
                            CharacterStyle:"Normal",
                            Alignment:"Left",
                            EndOfLineFlag:true,
                            Text:"More special characters (‰ƒˆ÷¸‹ﬂ)"
                        },
                        {
                            Color:"White",
                            CharacterWidth:"SingleWidth",
                            CharacterHeight:"SingleHeight",
                            CharacterStyle:"Normal",
                            Alignment:"Left",
                            EndOfLineFlag:true,
                            Text:""
                        }
                    ],
                    OutputFormat:"Text"
                },
                DocumentQualifier:"Document",
                ResponseMode:"PrintEnd"
            }
        }
    }
}